"""GMI Cloud provider profile."""

from hermes_cli import __version__ as _HERMES_VERSION
from providers import register_provider
from providers.base import ProviderProfile

gmi = ProviderProfile(
    name="gmi",
    aliases=("gmi-cloud", "gmicloud"),
    display_name="GMI Cloud",
    description="GMI Cloud — multi-model direct API (slash-form model IDs)",
    signup_url="https://www.gmicloud.ai/",
    env_vars=("GMI_API_KEY", "GMI_BASE_URL"),
    base_url="https://api.gmi-serving.com/v1",
    auth_type="api_key",
    # Attribution so GMI can identify traffic from Hermes Agent.
    # The generic profile.default_headers fallback in run_agent.py and
    # agent/auxiliary_client.py picks this up at client construction time.
    default_headers={"User-Agent": f"HermesAgent/{_HERMES_VERSION}"},
    default_aux_model="google/gemini-3.1-flash-lite-preview",
    fallback_models=(
        "google/gemini-3.8-flash",
        "zai-org/GLM-5.3-Flash",
        "Qwen/Qwen3.8-27B",
        "stepfun-ai/Step-3.7-Flash",
        "google/gemini-3.7-flash",
        "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
        "Qwen/Qwen3.8-Max",
        "deepseek-ai/DeepSeek-V4-Flash-0731",
        "anthropic/claude-opus-5",
        "google/gemini-3.6-flash",
        "google/gemini-3.5-flash-lite",
        "moonshotai/kimi-k3",
        "x-ai/grok-4.5",
        "openai/gpt-5.6-luna",
        "openai/gpt-5.6-terra",
        "openai/gpt-5.6-sol",
        "tencent/Hy3",
        "anthropic/claude-sonnet-5",
        "moonshotai/kimi-k2.7-code-highspeed",
        "zai-org/GLM-5.2-FP8",
        "anthropic/claude-fable-5",
        "MiniMaxAI/MiniMax-M3",
        "anthropic/claude-opus-4.8",
        "Qwen/Qwen3.7-Max",
        "google/gemini-3.5-flash",
        "XiaomiMiMo/MiMo-V2.5-Pro",
        "openai/gpt-5.5",
        "deepseek-ai/DeepSeek-V4-Pro",
        "anthropic/claude-opus-4.7",
        "zai-org/GLM-5.1-FP8",
        "zai-org/GLM-5-FP8",
        "openai/gpt-5.4-nano",
        "openai/gpt-5.4-mini",
        "MiniMaxAI/MiniMax-M2.7",
        "google/gemini-3.1-flash-lite-preview",
        "openai/gpt-5.4-pro",
        "openai/gpt-5.4",
        "google/gemini-3.1-pro-preview",
        "anthropic/claude-sonnet-4.6",
        "anthropic/claude-haiku-4.5",
        "anthropic/claude-opus-4.1",
        "anthropic/claude-sonnet-4",
        "anthropic/claude-opus-4.5",
        "anthropic/claude-sonnet-4.5",
        "anthropic/claude-opus-4.6",
        "deepseek-ai/DeepSeek-R1-0528",
        "deepseek-ai/DeepSeek-V3.2",
        "deepseek-ai/DeepSeek-V3-0324",
        "deepseek-ai/DeepSeek-V4.1-Flash",
        "deepseek-ai/DeepSeek-V4-Flash",
        "deepseek-ai/DeepSeek-V4-Flash-0731",
        "deepseek-ai/deepseek-v4-flash-vision-exp",
        "deepseek-ai/DeepSeek-V4-Pro-0813",
        "google/gemini-3-flash-preview",
        "google/gemma-4-26b-a4b-it",
        "google/gemma-4-31b-it",
        "openai/gpt-6-astra",
        "openai/gpt-oss-120b",
        "xai/grok4.6",
        "XiaomiMiMo/MiMo-V2.5",
        "MiniMaxAI/MiniMax-M2.5",
        "moonshotai/Kimi-K2.5",
        "moonshotai/Kimi-K2.6",
        "moonshotai/kimi-k2.7-code",
        "moonshotai/Kimi-K2-Instruct-0905",
        "moonshotai/Kimi-K2-Thinking",
        "nvidia/nemotron-3-ultra-550b-a55b",
        "zai-org/GLM-4.7-FP8",
        "Qwen/Qwen3.5-122B-A10B",
        "Qwen/Qwen3.5-27B",
        "Qwen/Qwen3.5-35B-A3B",
        "Qwen/Qwen3.5-397B-A17B",
        "Qwen/Qwen3.6-35B-A3B",
        "Qwen/Qwen3.6-Plus",
        "Qwen/Qwen3.6-Plus-2026-04-02",
        "Qwen/Qwen3.8-Flash",
        "Qwen/Qwen3.8-Max-0902",
        "Qwen/Qwen3-Next-80B-A3B-Instruct",
        "Qwen/Qwen3-Next-80B-A3B-Thinking",
        "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8",
        "Qwen/Qwen3-235B-A22B-Thinking-2507-FP8",
        "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
        "tencent/hy3-preview",
        "tencent/hy4-preview",
        "zai-org/GLM-5.3",
    ),
)

register_provider(gmi)
